/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 whatsapp.gltf -t
*/

import { useRef } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Curve030: THREE.Mesh;
    Curve030_1: THREE.Mesh;
  };
  materials: {
    ["default"]: THREE.MeshStandardMaterial;
    whatsapp: THREE.MeshStandardMaterial;
  };
};

const Whatsapp = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("whatsapp.gltf") as GLTFResult;

  const ref = useRef();

  useFrame((state) => {
    const t = state.clock.getElapsedTime();
    ref.current.rotation.z = -0.2 - (1 + Math.sin(t / 1.5)) / 20;
    ref.current.rotation.x = Math.cos(t / 4) / 8;
    ref.current.rotation.y = Math.sin(t / 4) / 8;
    ref.current.position.y = (1 + Math.sin(t / 1.5)) / 10;
  });

  return (
    <group {...props} ref={ref} dispose={null}>
      <mesh
        geometry={nodes.Curve030.geometry}
        material={materials["default"]}
      />
      <mesh
        geometry={nodes.Curve030_1.geometry}
        material={materials.whatsapp}
      />
    </group>
  );
};

export default Whatsapp;

useGLTF.preload("whatsapp.gltf");
